name: C++ GitHub Actions Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++

    - name: Compile code
      run: g++ -o addition addition.cpp

    - name: Run tests
      run: ./addition
